### ISSUE TITLE
UEL-001: Crash when externally blocking MAC using admin

### ISSUE THREAD

**Issue by adgoudsmit** [airwinb/unifi-events-listener#1]
: {
  "meta": {
    "rc": "ok",
    "message": "events"
  },
  "data": [
    {
      "client": "04:4e:af:f4:59:0d",
      "admin": "Admin[ad]",
      "site_id": "5b25507f8e16b3b07e11713f",
      "is_admin": true,
      "key": "EVT_WC_Blocked",
      "subsystem": "wlan",
      "time": 1580907334399,
      "datetime": "2020-02-05T12:55:34Z",
      "msg": "Client[04:4e:af:f4:59:0d] is blocked by Admin[ad]",
      "_id": "5e3abb46c6679800072f92f0"
    }
  ]
}
Traceback (most recent call last):
  File "unifi_events_listener.py", line 299, in <module>
    main()
  File "unifi_events_listener.py", line 287, in main
2020-02-05 13:55:36,469 INFO     1 events in event queue
    url_list = get_urls_to_call(user_event_url_list, event_list)
  File "unifi_events_listener.py", line 206, in get_urls_to_call
    if event['user'] == user_event_url_list[i]['event_user']:
KeyError: 'user'

Admin is used to block this mac adress, but seems to cause an issue in events listener.

**Comment by airwinb** [comment]
Resolved in version 0.2.0
