### ISSUE TITLE
UEL-1: Events not triggered after socket reconnect

### ISSUE THREAD

**Issue by adjego** [airwinb/unifi-events-listener#2]
When a socket reconnect occurs (reason unknown), it seems to be that there is no event triggered anymore. In the log it no longer shows an event has been noticed and no action is taken.

After a service restart it's resolved.

**Comment by airwinb** [comment]
Should be fixed in https://github.com/airwinb/unifi-events-listener/tree/UEL-1

**Comment by airwinb** [comment]
Fixed in version 0.3.0
